version: "3.9"

services:
  api:
    build: .
    container_name: devops_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase

db:
  image: postgres:15
  container_name: devops_db
  restart: always
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: mydatabase
  ports:
    - "5432:5432"